import os
import logging
from concurrent.futures import ThreadPoolExecutor
from ragret.utils.llm_adapter import LLMAdapter
import numpy as np
from numpy.typing import NDArray

# Logging configuration for debugging
logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(message)s"
)

class AnswerRelevancy:
    def __init__(self, 
                 provider:str, 
                 api_key: str | None = None, 
                 ollama_url: str | None = None, 
                 model: str | None = None,
                 embedding_model: str| None = None) -> None:
        
        supported_clients = ["openai","google","ollama"]
        self.provider = provider
        self.api_key = api_key or os.getenv("API_KEY")
        
        #Optional: model, ollama_url (for ollama use)
        self.ollama_url = ollama_url
        self.model = model
        self.embedding_model = embedding_model

        # self.provider must match any of the supported clients
        if self.provider not in supported_clients:
            raise ValueError(f"Incorrect LLM provider. Please choose from supported clients: {supported_clients}")
        if not self.api_key:
            raise ValueError("Please provide a valid API key")

        # Based on the provider 
        self.llm = LLMAdapter(provider=self.provider, 
                              api_key=self.api_key,
                              ollama_url=self.ollama_url,
                              model=self.model,
                              embedding_model=self.embedding_model)

# Function that takes an llm_answer as input 
# Returns n number of questions that could be questioned to get the same llm_answer output
    def _generate_artificial_questions(self, llm_answer: str, n) -> list[str]:
        prompt = f"""
You are generating questions that could be answered by the given response.

Rules:
- Generate exactly {n} distinct questions.
- Each question must be fully answerable by the response alone.
- Each question must cover a different main point of the response.
- Output each question separated by a dollar sign ($) with no spaces around it.
- Do NOT include explanations, numbering, or any other text.
- Use only the original language of the response.

Example:
Response: "We are open Monday to Friday 9am-6pm. Free shipping applies on orders over $50."
Output: "What are the opening hours?$When does free shipping apply?"

Response:
{llm_answer}
"""
        try:
            derived_questions = self.llm.generate(prompt)

            # Make the response a list that splits each sentence on '$'
            artificial_questions = derived_questions.split("$")
            for i in range(len(artificial_questions)):
                artificial_questions[i] = artificial_questions[i].rstrip()
            #logging.info(artificial_questions)
            return artificial_questions
        
        except Exception as error:
            logging.error(f"Error on Answer Relevancy |_generate_artificial_questions|: {error}")
            raise

# Function that given a text input, it computes the vector embedding of the input and returns it  
    def _compute_vector_embedding(self, input: str) -> NDArray[np.float32]:
        try:
            vector_embedding = self.llm.get_embedding(input=input)
            return np.array(vector_embedding)
        except Exception as error:
            logging.error(f"Error on Answer Relevancy |_compute_vector_embedding|: {error}")
            raise

# Main score answer relevancy function. Calls _generate_artificial_questions function and after making
# vector embeddings of the user query and the answers generated calculates the answer relevancy metric
# using the fomula: answer_relevancy = Σ(cosine_similarity) / n
    def score(self, user_query: str, llm_answer: str, n=3) -> dict:
        try:
            artificial_questions = self._generate_artificial_questions(llm_answer,n)

            # Create a pool of worker threads and using the .map() 
            # send the user query and the list of the questions generated by the llm to a separate thread 
            # so they can be turned into vector embeddings simultaneously
            with ThreadPoolExecutor() as executor:
                all_embeddings = list(executor.map(self._compute_vector_embedding, [user_query] + artificial_questions))

            # The returned result is a list containing the vector embeddings of the user query (on index 0)
            # and the vector embeddings of the n questions generated and the user input (from index 1 till n-1)
            
            query_embedding = all_embeddings[0]
            answer_embeddings = all_embeddings[1:]

            # For each question calculate the cosine similarity to the user query and add it to the cosine_similarity_sum
            cosine_similarity_sum = 0
            for answer_embedding in answer_embeddings:
                cosine_similarity = np.dot(query_embedding, answer_embedding) / (np.linalg.norm(query_embedding) * np.linalg.norm(answer_embedding))
                cosine_similarity_sum += cosine_similarity
            answer_relevancy = cosine_similarity_sum / n
            #logging.info(answer_relevancy)
            return {
                "score": float(answer_relevancy),
                "generated_questions": artificial_questions
            }
        
        except Exception as error:
            logging.error(f"Error on Answer Relevancy: |score|: {error}")
            raise
